apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-v2-test
spec:
  compositeTypeRef:
    apiVersion: v2.test.crossplane.io/v1
    kind: CoolXR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-v2-test
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      keyName: "cool-key"
